config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :clients
  resources :clients
  resources :currencies
  resources :expenses
  resources :finishes
  resources :finishes
  resources :accesories do
    get :autocomplete_accesory_name, :on => :collection
  end
  resources :elements
  resources :subassemblages
  resources :assemblages
  resources :materials
  get 'new_client' => 'clients#new'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get 'assemblage_price' => 'assemblages#price_calculator'
  resources :users

  

end

app/models/assemblage.rb
class Assemblage < ActiveRecord::Base
	has_one :material
    has_one :accesory
    has_one :finish
	has_many :subassemblage

	before_save :set_net_volume, :set_brut_volume, :set_net_surface, :set_brut_surface


    def material
        material = Material.find_by_id(self.material_id)  
    end

    def subassemblages_list
    	@subassemblages = Subassemblage.where("assemblage_id = ?", self.id)
    end

	def set_net_volume
		self.net_volume = BigDecimal.new("0.000")
		
		subassemblages_list.each do |s|
			self.net_volume = BigDecimal.new(self.net_volume) + BigDecimal.new(s.volume)
		end	
	end

    def set_brut_volume  	
        self.brut_volume = BigDecimal.new(self.net_volume / material.output_coefficient)
    end

    def set_net_surface
    	self.net_surface = BigDecimal.new("0.000")
        subassemblages_list.each do |s|
			self.net_surface = self.net_surface + s.surface
		end	
    end

    def set_brut_surface
        self.brut_surface = self.net_surface * 2

    end


end

app/controllers/assemblages_controller.rb
class AssemblagesController < ApplicationController
  before_action :set_assemblage, only: [:show, :edit, :update, :destroy]

  # GET /assemblages
  # GET /assemblages.json
  def index
    @assemblages = Assemblage.all
  end

  # GET /assemblages/1
  # GET /assemblages/1.json
  def show
    @assemblage = Assemblage.find(params[:id])
  end

  # GET /assemblages/new
  def new
    @assemblage = Assemblage.new
  end

  # GET /assemblages/1/edit
  def edit   
    @assemblage = Assemblage.find(params[:id])
    @subassemblages = Subassemblage.where("assemblage_id = ?", @assemblage.id)
  end

  def price_calculator
    @assemblage = Assemblage.find(params[:assemblage_id])
    @expenses = Expense.all
    @total_processing_cost_domestic = @expenses.sum(:domestic_value)
    @total_processing_cost_currency = @expenses.sum(:currency_value)

    @material = Material.find_by_id(@assemblage.material_id)
    @cost_material_prim_domestic = @material.price * @assemblage.brut_volume

    @processing_cost_domestic = @total_processing_cost_domestic * @assemblage.brut_volume
    @processing_cost_currency = @total_processing_cost_currency * @assemblage.brut_volume

    @total_cost_estimated_domestic = @cost_material_prim_domestic + @processing_cost_domestic

  end


  # POST /assemblages
  # POST /assemblages.json
  def create
    @assemblage = Assemblage.new(assemblage_params)

   if @assemblage.save
      flash[:success] = "Ansamblul a fost adaugat cu success!"
      redirect_to @assemblage
    else
      flash[:danger] = "Eroare!!"
      render 'new'
    end
  end

  # PATCH/PUT /assemblages/1
  # PATCH/PUT /assemblages/1.json
  def update
     
      if @assemblage.update(assemblage_params)
        flash[:success] = "Ansamblul a fost actualizat cu success!"
        redirect_to edit_assemblage_path
      else
        flash[:danger] = "Eroare!!"
        render 'new'
      
      end
    
  end

  # DELETE /assemblages/1
  # DELETE /assemblages/1.json
  def destroy
    @assemblage.destroy
    respond_to do |format|
      format.html { redirect_to assemblages_url, notice: 'Assemblage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assemblage
      @assemblage = Assemblage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assemblage_params
      params.require(:assemblage).permit(:name,:code,:material_id,:finish_id,:accesory_id,:accesory_name,:height,:width,:depth,:net_volume,:net_surface,:brut_volume,:brut_surface)
    end

     

end

app/helpers/assemblages_helper.rb
module AssemblagesHelper
	def find_material(assemblage)
	end
end

app/views/assemblages/_form.html.erb
<%= form_for(@assemblage) do |f| %>
  <% if @assemblage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assemblage.errors.count, "error") %> prohibited this assemblage from being saved:</h2>

      <ul>
      <% @assemblage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<table class="table">
  <thead>
    <tr>
       <th><%= f.label :material_id %><br></th>
       <th><%= f.label :code %></th>
      <th><%= f.label :name %></th>   
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> <%= f.collection_select(:material_id, Material.all, :id, :name) %></td>
      <td><%= f.text_field :code %></td>
      <td><%= f.text_field :name %></td>
    </tr>
  </tbody>
</tr>

</table>

<table class="table">
  <thead>
    <tr>
    <th> <%= f.label :height %></th>
    <th> <%= f.label :depth %></th>
    <th> <%= f.label :width %></th>
  </tr>
   </thead> 
   <tbody>
    <tr>
      <td><%= f.number_field :height %></td>
      <td><%= f.number_field :depth %></td>
      <td><%= f.number_field :width %></td>
    </tr> 
   </tbody> 
</table> 

<table class="table">
  <thead>
    <tr>
      <th> Finisaj </th>
      <th> Accesorii </th>
    </tr>
  </theadL>
  <tbody>
    <tr>
       <td> <%= f.collection_select(:finish_id, Finish.all, :id, :name) %></td>
       <td> <%=  f.autocomplete_field :accesory_name, autocomplete_accesory_name_accesories_path, :size => 50, :id_element => '#accesory_id' %>
      </td>

    </tr>
  </tbody>
</table>

   


  <div class="actions">
    <%= f.submit %>   

    <% if @assemblage.persisted? %>
      <%= render :partial => "subassemblages/index" if @subassemblages %>

      <%= link_to "<i class='glyphicon glyphicon-plus'></i>&nbsp; Adauga Subasamblaj".html_safe, new_subassemblage_path(:assemblage_id=> @assemblage.id), :class => "btn btn-primary pull-left" %>

       <%= link_to "<i class='glyphicon glyphicon-plus'></i>&nbsp; Calculeaza Pret".html_safe, assemblage_price_path(:assemblage_id=> @assemblage.id), :class => "btn btn-default pull-left" %>

       
    <% end %>    
  </div>


<% end %>

app/views/assemblages/_volumes.html.erb
<table class="table">
  <thead>
    <tr>
    <td>Volum Net</td>
    <td><%= @assemblage.net_volume %></td>
  </tr>
  <tr>
    <td>Suprafata Neta</td>
    <td><%= @assemblage.net_surface %></td>
  </tr>
  <tr>
    <td>Volum Brut</td>
    <td><%= @assemblage.brut_volume %></td>
  </tr>
  <tr>
     <td>Suprafata Bruta </td>
     <td><%= @assemblage.brut_surface %></td>
  </tr>
  </thead> 
</table>

app/views/assemblages/edit.html.erb
<h1>Ansamblu</h1>

<%= render 'form' %>

 <%= link_to "<i class='glyphicon glyphicon-check'></i>&nbsp; Arata Detalii".html_safe, @assemblage, :class => "btn btn-default pull-left" %>

 <%= link_to "<i class='glyphicon glyphicon-arrow'></i>&nbsp; Inapoi".html_safe, assemblages_path, :class => "btn btn-default pull-left" %>

app/views/assemblages/index.html.erb
<% provide(:title, 'Lista Ansambluri') %>

<h1>Ansambluri</h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Cod</th>
      <th>Nume<th>
      <th>Consumuri</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assemblages.each do |assemblage| %>
      <tr>
        <td><%=assemblage.code%></td>
        <td><%=assemblage.name%></td>
        <td colspan="3"><%=assemblage.height%> X <%=assemblage.width%> X <%=assemblage.depth%></td>
        <td colspan="3"><%= link_to 'Arata detalii', assemblage %>
        <%= link_to 'Actualizeaza', edit_assemblage_path(assemblage) %>
        <%= link_to 'Sterge', assemblage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adauga Ansamblu', new_assemblage_path %>

app/views/assemblages/new.html.erb
<h1>New Assemblage</h1>

<%= render 'form' %>

<%= link_to 'Inapoi', assemblages_path %>

app/views/assemblages/price_calculator.erb
<h1> Calculator Preturi Ansamblu </h1>
<h2><%= @assemblage.code %> <%= @assemblage.name %> </h2>
 <%= render 'volumes' %>

 <h2> Cost materie prima consumata: <%= @cost_material_prim_domestic %> </h2>

 <h2> Total cost procesare valuta domestica (RON) <%= @processing_cost_domestic %></h2>

app/views/assemblages/show.html.erb
<% provide(:title, 'Detalii Ansambluri') %>

<h1>Detalii Ansamblu</h1>
<%= render 'form' %>


<%= link_to 'Actualizeaza', edit_assemblage_path(@assemblage) %> |
<%= link_to 'Inapoi', assemblages_path %>