config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :clients
  resources :clients
  resources :currencies
  resources :expenses
  resources :finishes
  resources :finishes
  resources :accesories do
    get :autocomplete_accesory_name, :on => :collection
  end
  resources :elements
  resources :subassemblages
  resources :assemblages
  resources :materials
  get 'new_client' => 'clients#new'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get 'assemblage_price' => 'assemblages#price_calculator'
  resources :users

  

end

app/models/element.rb
class Element < ActiveRecord::Base
	belongs_to :subassemblage

	before_save :set_volume, :set_surface

	def set_volume
		self.volume = self.height * self.width * self.depth * self.quantity / 100000000
	end

	def set_surface
		self.surface = self.height * self.width * self.quantity / 1000000
	end

end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: [:show, :edit, :update, :destroy]

  # GET /elements
  # GET /elements.json
  def index
    @elements = Element.all
  end

  # GET /elements/1
  # GET /elements/1.json
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(element_params)

    if @element.save
      flash[:success] = "Elementul a fost adaugat cu success!"
      redirect_to @element
      set_subassemblage.save
    else
      flash[:success] = "Eroare!!"
      render 'new'
    end
  end

  # PATCH/PUT /elements/1
  # PATCH/PUT /elements/1.json
  def update
    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to @element, notice: 'Element was successfully updated.' }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { render :edit }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element.destroy
    respond_to do |format|
      format.html { redirect_to elements_url, notice: 'Element was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def element_params
      params.require(:element).permit(:name, :height, :width, :depth, :quantity, :subassemblage_id)
    end

    def set_subassemblage
      if @element.persisted?
        @subassemblage = Subassemblage.find(@element.subassemblage_id)
      else  
        @subassemblage = Subassemblage.find(params[:subassemblage_id])
      end
    end


    
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/elements/_actions.html.erb
<%= link_to 'Arata detalii', @element %> |
<%= link_to 'Inapoi', edit_subassemblage_path(@element.subassemblage_id) %>

app/views/elements/_form.html.erb
<%= form_for(@element) do |f| %>
  <% if @element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% @element.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @element.persisted? %>
  <%= f.hidden_field :subassemblage_id, value: @element.subassemblage_id%>
<%else %>
  <%= f.hidden_field :subassemblage_id, value: params[:subassemblage_id] %>
<%end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.text_field :width %>
  </div>
  <div class="field">
    <%= f.label :depth %><br>
    <%= f.text_field :depth %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    
    <%= f.submit "Inregistrare" , :class => 'btn btn-primary pull-right'%>
  </div>
<% end %>

app/views/elements/_index.html.erb
<% provide(:title, 'Lista elemente') %>
<h1>Lista elemente</h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Height</th>
      <th>Width</th>
      <th>Depth</th>
      <th>Quantity</th>
      <th colspan="3"> Actiuni</th>
    </tr>
  </thead>

  <tbody>
    <% @elements.each do |element| %>
      <tr>
        <td><%= element.name %></td>
        <td><%= element.height %></td>
        <td><%= element.width %></td>
        <td><%= element.depth %></td>
        <td><%= element.quantity %></td>
        <td><%= link_to 'Arata detalii', element %></td>
        <td><%= link_to 'Actualizeaza', edit_element_path(element) %></td>
        <td><%= link_to 'Sterge', element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/elements/edit.html.erb
<h1>Actualizare Element</h1>

<%= render 'form' %>

<%= render 'actions' %>

app/views/elements/index.html.erb
<%= render 'index' %>

<br>
<%= link_to 'Adauga Element', new_element_path %>

app/views/elements/new.html.erb
<h1>Adaugare Element</h1>

<%= render 'form' %>

<%= link_to 'Inapoi', elements_path %>

app/views/elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @element.name %>
</p>

<p>
  <strong>Height:</strong>
  <%= @element.height %>
</p>

<p>
  <strong>Width:</strong>
  <%= @element.width %>
</p>

<p>
  <strong>Depth:</strong>
  <%= @element.depth %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @element.quantity %>
</p>

<%= link_to 'Actualizeaza', edit_element_path(@element) %> |
<%= link_to 'Inapoi', edit_subassemblage_path(@element.subassemblage_id) %>