config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :clients
  resources :clients
  resources :currencies
  resources :expenses
  resources :finishes
  resources :finishes
  resources :accesories do
    get :autocomplete_accesory_name, :on => :collection
  end
  resources :elements
  resources :subassemblages
  resources :assemblages
  resources :materials
  get 'new_client' => 'clients#new'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get 'assemblage_price' => 'assemblages#price_calculator'
  resources :users

  

end

app/models/subassemblage.rb
class Subassemblage < ActiveRecord::Base
	has_many :element
	belongs_to :assemblage

	before_save :set_volume, :set_surface

    def elements_list
    	@elements = Element.where("subassemblage_id = ?", self.id)
    end

	def set_volume
		if elements_list.empty?
			self.volume = self.height * self.width * self.depth * self.quantity / 1000000000
		else
			self.volume = BigDecimal.new("0.000")
			elements_list.each do |e|
				self.volume = self.volume + e.volume
			end

		end
	end

	def set_surface
		self.surface = self.height * self.width * self.quantity / 1000000
	end

end

app/controllers/subassemblages_controller.rb
class SubassemblagesController < ApplicationController
  before_action :set_subassemblage, only: [:show, :edit, :update, :destroy]
  
  # GET /subassemblages
  # GET /subassemblages.json
  def index
    @subassemblages = Subassemblage.all
  end

  # GET /subassemblages/1
  # GET /subassemblages/1.json
  def show

  end

  # GET /subassemblages/new
  def new
    @subassemblage = Subassemblage.new
  end

  # GET /subassemblages/1/edit
  def edit
    @subassemblage = Subassemblage.find(params[:id])  
    @elements = Element.where("subassemblage_id = ?", @subassemblage.id)   
  end

  # POST /subassemblages
  # POST /subassemblages.json
  def create
    
    @subassemblage = Subassemblage.create(subassemblage_params)
   
    if @subassemblage.save
      flash[:success] = "Subansamblul a fost adaugat cu success!"
      redirect_to @subassemblage
      set_assemblage.save
    else
      flash[:success] = "Eroare!!"
      render 'new'
    end
  end

  # PATCH/PUT /subassemblages/1
  # PATCH/PUT /subassemblages/1.json
  def update  
      if @subassemblage.update(subassemblage_params)
        flash[:success] = "Subansamblul a fost adaugat cu success!"
        redirect_to @subassemblage
        set_assemblage.save
      else
        flash[:success] = "Eroare!!"
        render 'edit'
      end
  end

  # DELETE /subassemblages/1
  # DELETE /subassemblages/1.json
  def destroy
    elements_list.delete_all
    @subassemblage.destroy

    respond_to do |format|
      format.html { redirect_to subassemblages_url, notice: 'Subassemblage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subassemblage
      @subassemblage = Subassemblage.find(params[:id])
    end

   # Never trust parameters from the scary internet, only allow the white list through.
    def subassemblage_params
       params.require(:subassemblage).permit(:name,:code,:material_id,:height,:width,:depth, :quantity, :assemblage_id)
    end

    def set_assemblage
      if @subassemblage.persisted?
        @assemblage = Assemblage.find(@subassemblage.assemblage_id)
      else  
        @assemblage = Assemblage.find(params[:assemblage_id])
      end
    end
end

app/helpers/subassemblages_helper.rb
module SubassemblagesHelper
	 
end

app/views/subassemblages/_form.html.erb
<%= form_for(@subassemblage) do |f| %>
  <% if @subassemblage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subassemblage.errors.count, "error") %> prohibited this subassemblage from being saved:</h2>

      <ul>
      <% @subassemblage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% if @subassemblage.persisted? %>
  <%= f.hidden_field :assemblage_id, value: @subassemblage.assemblage_id%>
<%else %>
  <%= f.hidden_field :assemblage_id, value: params[:assemblage_id] %>
<%end %>
<div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>


   <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>

 <div class="field">
    <%= f.label :width %><br>
    <%= f.number_field :width %>
  </div>

   <div class="field">
    <%= f.label :depth %><br>
    <%= f.number_field :depth %>
  </div>

 <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
     <% if @subassemblage.persisted? %>
      <%= render :partial => "elements/index" if @elements %>
      <%= link_to "Add Element ", new_element_path(:subassemblage_id=> @subassemblage.id)%>
      <% end %>
  </div>
<% end %>

app/views/subassemblages/_index.html.erb
<table class="table table-stripped">
  <thead>

    <tr>
      <th>Cod</th>
      <th>Nume</th>
      <th>Consumuri</th>
      <th>Nr bucati </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subassemblages.each do |subassemblage| %>
      <tr>
        <td><%= subassemblage.code %> </td>
        <td><%= subassemblage.name %> </td>
        <td><%= subassemblage.height %> X <%= subassemblage.width%> X <%= subassemblage.depth %> </td>
        <th><%= subassemblage.quantity %>
        <td colspan="3"><%= link_to 'Arata detalii', subassemblage %>
        <%= link_to 'Actualizeaza', edit_subassemblage_path(subassemblage) %>
        <%= link_to 'Sterge', subassemblage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/subassemblages/edit.html.erb
<h1>Actualizare Subansamblu</h1>

<%= render 'form' %>

<%= link_to 'Arata detalii', @subassemblage %> |
<%= link_to 'Inapoi', edit_assemblage_path(@subassemblage.assemblage_id) %>

app/views/subassemblages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subassemblages</h1>

<%= render 'index' %>

<br>

<%= link_to 'New Subassemblage', new_subassemblage_path %>

app/views/subassemblages/new.html.erb
<h1>New Subassemblage</h1>

<%= render 'form' %>

<%= link_to 'Back', subassemblages_path %>

app/views/subassemblages/show.html.erb
<% provide(:title, @subassemblage.name) %>
<h1>Detalii Subansamblu</h1>

<%= render 'form' %>

<%= link_to 'Actualizeaza', edit_subassemblage_path(@subassemblage) %> |
<%= link_to 'Back', edit_assemblage_path(@subassemblage.assemblage_id	) %>