config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :clients
  resources :clients
  resources :currencies
  resources :expenses
  resources :finishes
  resources :finishes
  resources :accesories do
    get :autocomplete_accesory_name, :on => :collection
  end
  resources :elements
  resources :subassemblages
  resources :assemblages
  resources :materials
  get 'new_client' => 'clients#new'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  get 'assemblage_price' => 'assemblages#price_calculator'
  resources :users

  

end

app/models/currency.rb
class Currency < ActiveRecord::Base
	belongs_to :expense
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]

  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
  end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end

  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:code, :name, :rate)
    end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<%= form_for(@currency) do |f| %>
  <% if @currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% @currency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing Currency</h1>

<%= render 'form' %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rate de schimb valutar </h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Cod</th>
      <th>Nume</th>
      <th>Rata de schimb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @currencies.each do |currency| %>
      <tr>
        <td><%= currency.code %></td>
        <td><%= currency.name %></td>
        <td><%= currency.rate %></td>
        <td><%= link_to 'Show', currency %> |
        <%= link_to 'Edit', edit_currency_path(currency) %> |
        <%= link_to 'Destroy', currency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adauga Moneda', new_currency_path %>

app/views/currencies/new.html.erb
<h1>New Currency</h1>

<%= render 'form' %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @currency.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @currency.name %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @currency.rate %>
</p>

<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>